spring:
  datasource:
    url: jdbc:postgresql://db:5432/wms-service
    username: postgres
    password: tawkenskiy
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update   # ??? dev ?????????, ??? prod ? validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never
