name: Deploy WRM System

on:
  push:
    branches: [ "main" ] # Сценарий сработает при каждом push в main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./app/Dockerfile # Убедись, что путь к Dockerfile верный
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/wms-service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push # Запускается только после успешной сборки
    steps:
      - name: Install Cloudflared
        run: |
          wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb

      - name: Deploy via SSH over Cloudflare
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }} # Это ssh.islom.online
          username: ${{ secrets.SSH_USER }} # Это islom
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Магия для прохода через туннель:
          proxy_command: cloudflared access ssh --hostname ${{ secrets.SSH_HOST }}
          script: |
            cd /home/islom/IdeaProjects/wrm-system
            # Обновляем только сервис приложения
            docker compose pull app
            docker compose up -d app
            # Удаляем старые ненужные образы
            docker image prune -f