name: Deploy WRM System

on:
  push:
    branches: [ "master" ] # Сценарий сработает при каждом push в main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./app/Dockerfile # Убедись, что путь к Dockerfile верный
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/wms-service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Setup SSH key
        run: |
          mkdir -p $HOME/.ssh
          cat <<'EOF' | tr -d '\r' > $HOME/.ssh/id_rsa
            ${{ secrets.SSH_PRIVATE_KEY }}
            EOF
            chmod 600 $HOME/.ssh/id_rsa
            ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> $HOME/.ssh/known_hosts

      - name: Debug SSH setup
        run: |
         echo "HOME=$HOME"
           whoami
           pwd
           mkdir -p ~/.ssh



      - name: Deploy Docker Compose
        run: |
          ssh -i ~/.ssh/id_rsa -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
             cd ~/IdeaProjects/wrm-system &&
             docker compose pull &&
             docker compose up -d wrm-system-nginx &&
             docker image prune -f
            "