name: Deploy WRM System

on:
  push:
    branches: [ "master" ] # Сценарий сработает при каждом push в main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./app/Dockerfile # Убедись, что путь к Dockerfile верный
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/wms-service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Install cloudflared
        run: |
          wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb

      - name: Deploy via SSH (Direct Tunnel)
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          # Создаем папку для ключей
          mkdir -p ~/.ssh
          
          # Записываем ключ в файл
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          
          # Настраиваем конфиг SSH для использования туннеля
          cat <<EOF > ~/.ssh/config
          Host $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/id_ed25519
            StrictHostKeyChecking no
            ProxyCommand /usr/local/bin/cloudflared access ssh --hostname %h
          EOF
          
          # Подключаемся и выполняем деплой
          ssh $SSH_HOST << 'ENDSSH'
            cd /home/islom/IdeaProjects/wrm-system
            docker compose pull app
            docker compose up -d app
            docker image prune -f
          ENDSSH